@echo off
echo Starting DBx Connector Vue in Development Mode...
echo.
echo [1/2] Starting Vite dev server...
start "Vite Dev Server" cmd /c "cd frontend && npm run dev"

echo [2/2] Waiting 5 seconds for Vite to start...
timeout /t 5 /nobreak >nul

echo Starting Electron...
electron . --dev
